# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.curve_tab = QtWidgets.QWidget()
        self.curve_tab.setObjectName("curve_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.curve_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.matplotlibcurveWidget = MatplotlibCurveWidget(self.curve_tab)
        self.matplotlibcurveWidget.setFigureAutoScale(True)
        self.matplotlibcurveWidget.setFigureBorderLineWidth(1.0)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matplotlibcurveWidget.setFigureXYlabelFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matplotlibcurveWidget.setFigureTitleFont(font)
        self.matplotlibcurveWidget.setProperty("figureDPI", 120.0)
        self.matplotlibcurveWidget.setFigureGridToggle(True)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matplotlibcurveWidget.setFigureXYticksFont(font)
        self.matplotlibcurveWidget.setProperty("figureLineAlpha", 0.9)
        self.matplotlibcurveWidget.setProperty("figureLineWidth", 2.0)
        self.matplotlibcurveWidget.setObjectName("matplotlibcurveWidget")
        self.verticalLayout_3.addWidget(self.matplotlibcurveWidget)
        self.tabWidget.addTab(self.curve_tab, "")
        self.image_tab = QtWidgets.QWidget()
        self.image_tab.setObjectName("image_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.image_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.matplotlibimageWidget = MatplotlibImageWidget(self.image_tab)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matplotlibimageWidget.setFigureXYlabelFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matplotlibimageWidget.setFigureTitleFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matplotlibimageWidget.setFigureXYticksFont(font)
        self.matplotlibimageWidget.setObjectName("matplotlibimageWidget")
        self.verticalLayout_2.addWidget(self.matplotlibimageWidget)
        self.tabWidget.addTab(self.image_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.server_url_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.server_url_lineEdit.sizePolicy().hasHeightForWidth())
        self.server_url_lineEdit.setSizePolicy(sizePolicy)
        self.server_url_lineEdit.setText("")
        self.server_url_lineEdit.setObjectName("server_url_lineEdit")
        self.horizontalLayout.addWidget(self.server_url_lineEdit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spectrum_cbb = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spectrum_cbb.sizePolicy().hasHeightForWidth())
        self.spectrum_cbb.setSizePolicy(sizePolicy)
        self.spectrum_cbb.setObjectName("spectrum_cbb")
        self.horizontalLayout.addWidget(self.spectrum_cbb)
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.daq_freq_sbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.daq_freq_sbox.setDecimals(1)
        self.daq_freq_sbox.setMinimum(0.1)
        self.daq_freq_sbox.setMaximum(100.0)
        self.daq_freq_sbox.setProperty("value", 1.0)
        self.daq_freq_sbox.setObjectName("daq_freq_sbox")
        self.horizontalLayout.addWidget(self.daq_freq_sbox)
        self.daq_rate_lbl = QtWidgets.QLabel(self.centralwidget)
        self.daq_rate_lbl.setText("")
        self.daq_rate_lbl.setObjectName("daq_rate_lbl")
        self.horizontalLayout.addWidget(self.daq_rate_lbl)
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout.addWidget(self.update_btn)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 30))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionContents = QtWidgets.QAction(MainWindow)
        self.actionContents.setObjectName("actionContents")
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.actionContents)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionAbout_Qt.triggered.connect(MainWindow.onAboutQt)
        self.actionE_xit.triggered.connect(MainWindow.close)
        self.action_About.triggered.connect(MainWindow.onAbout)
        self.update_btn.clicked.connect(MainWindow.on_update_data)
        self.server_url_lineEdit.returnPressed.connect(
            MainWindow.on_update_url)
        self.pushButton.toggled['bool'].connect(
            MainWindow.on_toggle_auto_update)
        self.pushButton.toggled['bool'].connect(self.update_btn.setDisabled)
        self.pushButton.toggled['bool'].connect(self.spectrum_cbb.setDisabled)
        self.pushButton.toggled['bool'].connect(
            self.server_url_lineEdit.setDisabled)
        self.daq_freq_sbox.valueChanged['double'].connect(
            MainWindow.on_update_daqrate)
        self.pushButton.toggled['bool'].connect(self.daq_rate_lbl.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.matplotlibcurveWidget.setFigureXlabel(
            _translate("MainWindow", "X"))
        self.matplotlibcurveWidget.setFigureYlabel(
            _translate("MainWindow", "Y"))
        self.matplotlibcurveWidget.setProperty(
            "figureLineDrawStyle", _translate("MainWindow", "steps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.curve_tab),
                                  _translate("MainWindow", "Page 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.image_tab),
                                  _translate("MainWindow", "Page 2"))
        self.label_2.setText(_translate("MainWindow", "Server Address"))
        self.label.setText(_translate("MainWindow", "Spectrum Names"))
        self.label_3.setText(_translate("MainWindow", "DAQ Rate"))
        self.update_btn.setText(_translate("MainWindow", "Update"))
        self.pushButton.setText(_translate("MainWindow", "Auto Update"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_About.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionContents.setText(_translate("MainWindow", "Contents"))
        self.actionContents.setShortcut(_translate("MainWindow", "F1"))


from mpl4qt.widgets.mplcurvewidget import MatplotlibCurveWidget
from mpl4qt.widgets.mplimagewidget import MatplotlibImageWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
